# Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu


# TBH: Task Bar Hero and similar idle games rules
$taskbarGames = ^(steam_app_3678970|TBH: Task Bar Hero)$

windowrule = float 1, match:class $taskbarGames
windowrule = border_size 0, match:class $taskbarGames
windowrule = no_blur 1, match:class $taskbarGames
windowrule = move 100%-w 100%-h, match:class $taskbarGames
windowrule = opacity 0.7 override 0.1 override, match:class $taskbarGames
windowrule = workspace special:tbh, match:class $taskbarGames


# Disable background dim and blur when opening special workspaces
decoration {
    dim_special = 0.0
    blur {
        special = false
    }
}
